server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/budget
    username: budget
    password: budget

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug